### ISSUE TITLE
Not working with CUDA 11 as nvidia-smi format is change

### ISSUE THREAD

**Issue by eyalrot** [rossumai/nvgpu#14]
stop working with CUDA 11
format is change need to start from line 8 and junp 4 lines per each GPU

**Comment by Felix-Petersen** [comment]
I fixed it.... See [this PR](https://github.com/rossumai/nvgpu/pull/15) or [my fork](https://github.com/Felix-Petersen/nvgpu).

**Comment by bzamecnik** [comment]
Should be fixed now in v0.9.0 thanks to @Felix-Petersen. 🙏  Please test it as I don't have CUDA 11.

**Comment by bzamecnik** [comment]
Tested on CUDA 11. Fine.
