### ISSUE TITLE
pip install -U is a little presumptuous isn't it?

### ISSUE THREAD

**Issue by spdavern** [rossumai/nvgpu#27]
I really appreciate the nvgpu tool!  Thank you.
Your [installation instructions](https://github.com/rossumai/nvgpu/blob/master/README.md) direct use of the -U or --upgrade pip flag.  Considering, this may upgrade a user's environment in substantial ways they may not prefer, is it really necessary or appropriate?  Trusting users that aren't aware of what the -U flag does could end up using an environment different from what they wanted, which was just to add the nvgpu functionality. I'm guessing [hoping] it resolves issues you've experienced but it seems like these would be solved a different way. Can you let us know why you've directed that?

**Comment by bzamecnik** [comment]
Thank your, fixed in 9655af3971d4a0401d395ae9f44e715a1e977b2f.
