### ISSUE TITLE
Python3 support

### ISSUE THREAD

**Issue by oridonner** [rossumai/nvgpu#7]
When will this project be supported in Python3?

**Comment by bzamecnik** [comment]
I'm afraid that only after NVIDIA supports Python 3 in the underlying py-nvml library or anybody makes an alternative binding.

**Comment by mabrowning** [comment]
Looks like there is one: https://github.com/nicolargo/nvidia-ml-py3.

That said, I was able to use `nvgpu` with python3 with only slight tweaks to `pynvml.py` (`print` → `print()` )

**Comment by bzamecnik** [comment]
That sound perfect!

**Comment by bzamecnik** [comment]
Nvidia ML for Python:

- nvidia-ml-py 375.53.1
  - works on python 2 only
- nvidia-ml-py3 7.352.0
  - does not work at all
- pynvml 8.0.1
  - needs python >=3.6

**Comment by bzamecnik** [comment]
There's also a nice new project `gpustat` that does pretty the same as this one (+some extras): https://github.com/wookayin/gpustat. It uses new `pynvml` and thus works only in Python 3.6+.

In addition there's compiled `nvtop` tool: https://github.com/Syllo/nvtop

**Comment by bzamecnik** [comment]
OK, I switched to select the compatible `pynvml` package for given Python version and modified the code to support Python 3. It works in all 2.7, 3.5, 3.6+. Released in `nvgpu-0.8.0`.
